version: '3.8'

services:

  server:
    build: .
    ports:
      - "8002:8000"
    depends_on:
      - redis
    volumes:
      - ./src:/Reminder_App
    command: "python ./manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/Reminder_App

  celery-worker:
    build: .
    depends_on:
      - redis
    volumes:
      - ./src:/Reminder_App
    command: "celery -A project worker -l info"


volumes:
  redis_data:










