# Generated by Django 3.1.14 on 2022-07-21 11:41

from django.db import migrations, models
import reminder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_reminder', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=60)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_notification', models.DateField()),
                ('time_notification', models.TimeField(default=reminder.models.Notification.default_start_time, max_length=16)),
            ],
        ),
    ]
