# Generated by Django 4.0.5 on 2022-07-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_notification_date_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
