# Generated by Django 4.0.5 on 2022-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_remove_notification_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_mail',
            field=models.EmailField(default='SOME STRING', max_length=60),
        ),
    ]
