# Generated by Django 4.0.5 on 2022-07-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_notification_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_notification',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_notification',
            field=models.DateField(),
        ),
    ]
