# Generated by Django 4.0.5 on 2022-07-06 15:32

from django.db import migrations, models
import reminder.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_notification_time_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_notification',
            field=models.TimeField(default=reminder.models.Notification.default_start_time),
        ),
    ]
