# Generated by Django 3.1.14 on 2022-07-20 14:18

from django.db import migrations, models
import reminder.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_alter_notification_time_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text_reminder',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_notification',
            field=models.CharField(default=reminder.models.Notification.default_start_time, max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_mail',
            field=models.EmailField(max_length=60),
        ),
    ]
